name = "foxcloud"
main = "dist/worker.js"
compatibility_date = "2024-09-23"

[build]
command = "npm run build"

# Development configuration
[vars]
UUID = "cbfddc6f-f4e2-4d4f-82e8-3adc6567cd76"
PROXY_IP = "104.19.98.71:443,162.159.153.42:443,162.159.153.156:443,172.66.45.9:443,104.18.128.25:443,162.159.136.94:443,104.19.144.212:443,172.66.40.99:443,162.159.39.250:443,104.27.62.243:443,2606:4700:3036:ef:3f32:9601:b705:e94b:443"
